# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20171111_0102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bets',
            new_name='Bet',
        ),
    ]
