# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20171111_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='email',
        ),
        migrations.RemoveField(
            model_name='team',
            name='password',
        ),
    ]
