# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20171111_1200'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bet',
            unique_together=set([('game', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('team1', 'team2', 'date')]),
        ),
    ]
