# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20171111_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='prob1',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='bet',
            name='prob2',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='prob1',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='prob2',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
