# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20171115_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='team1',
            new_name='team0',
        ),
    ]
