# Generated by Django 2.0 on 2017-12-07 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_auto_20171207_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='game',
        ),
        migrations.DeleteModel(
            name='Forecast',
        ),
    ]
