# Generated by Django 2.0 on 2017-12-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_result_committed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='points',
            field=models.SmallIntegerField(default=0),
        ),
    ]
