# Generated by Django 2.0 on 2017-12-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_auto_20171207_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
