# Generated by Django 2.0 on 2017-12-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_auto_20171207_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='points',
            field=models.IntegerField(default=-1),
        ),
    ]
