# Generated by Django 2.0 on 2017-12-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_auto_20171207_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='flag',
            field=models.CharField(default='xx', max_length=200),
        ),
    ]
