# Generated by Django 2.0 on 2017-12-08 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0026_auto_20171208_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueuser',
            name='asked_to_join_league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asked_to_join_league', to='games.League'),
        ),
        migrations.AddField(
            model_name='leagueuser',
            name='invited_by_league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_by_league', to='games.League'),
        ),
        migrations.AlterField(
            model_name='leagueuser',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league', to='games.League'),
        ),
    ]
