# Generated by Django 2.0 on 2017-12-08 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0028_auto_20171208_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueAsked',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.League')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueInvited',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.League')),
            ],
        ),
        migrations.AlterField(
            model_name='leagueuser',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.League'),
        ),
        migrations.RemoveField(
            model_name='leagueuser',
            name='asked_to_join_league',
        ),
        migrations.RemoveField(
            model_name='leagueuser',
            name='invited_by_league',
        ),
        migrations.AlterUniqueTogether(
            name='leagueuser',
            unique_together={('user', 'league')},
        ),
    ]
