# Generated by Django 2.0 on 2017-12-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0029_auto_20171208_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueasked',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leagueinvited',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
