# Generated by Django 2.0 on 2017-12-11 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0030_auto_20171208_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagueinvited',
            name='league',
        ),
        migrations.RemoveField(
            model_name='leagueinvited',
            name='user',
        ),
        migrations.DeleteModel(
            name='LeagueInvited',
        ),
    ]
