# Generated by Django 2.0 on 2017-12-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0031_auto_20171211_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='user_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='league',
            name='kind',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='league',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
