# Generated by Django 2.0.1 on 2018-03-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_auto_20171211_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name_pt',
            field=models.CharField(default='xx', max_length=200),
        ),
    ]
